DB_HOST=localhost
DB_NAME=carebridge
DB_USER=postgres
DB_PASSWORD=postgres
DB_SSLMODE=disable

FRONTEND_ORIGIN=http://localhost:5173

ISSUER=carebridge
TOKEN_EXPIRE_TIME=3600000
SECRET_KEY=CarebridgeHemmeligNoegle2026Team6