### Get server status (test route)
GET http://localhost:7070/api/
Accept: application/json

### Create new journal entry (multipart upload)
POST http://localhost:7070/api/journalentries
Authorization: Bearer faketoken
Content-Type: multipart/form-data; boundary=---123

---123
Content-Disposition: form-data; name="metadata"

{
  "journalId": 1,
  "title": "Observation of morning routine",
  "type": "DAILY_NOTE",
  "content": "Resident was calm and cooperative. Had breakfast at 8:30.",
  "risk": "LOW"
}
---123
Content-Disposition: form-data; name="files"; filename="observation.pdf"
Content-Type: application/pdf

< ./src/test/resources/files/observation.pdf
---123--

### Create journal entry with no files
POST http://localhost:7070/api/journals/1/journal-entries
Content-Type: application/json

{
  "journalId": 1,
  "title": "Observation of morning routine",
  "content": "Resident was calm and cooperative. Had breakfast at 8:30.",
  "riskAssessment": "LOW",
  "authorUserId": 3,
  "entryType": "DAILY"
}
### Remember that authorUserId should correspond to an existing user in your test database. and is hardcoded in controller
### Create a test user
POST http://localhost:7070/api/users
Content-Type: application/json

{
  "email": "test.careworker@example.com",
  "name": "Test CareWorker"
}

### Edit a journal entry - where window is closed
PATCH http://localhost:7070/api/journals/1/journal-entries/8
Content-Type: application/json

{
  "content": "Updated observation: resident was alert and cooperative after breakfast. No incidents observed."
}


### Edit a journal entry - where window is NOT closed
PATCH http://localhost:7070/api/journals/1/journal-entries/14
Content-Type: application/json

{
  "content": "Updated observation: resident was alert and cooperative after breakfast. No incidents observed."
}

### Get all journalEntry IDs for journal 1
GET http://localhost:7070/api/journals/1/journal-entries

### Get specific journal entry by ID
GET http://localhost:7070/api/journals/1/journal-entries/8

### Create new resident
POST http://localhost:7070/api/residents/create
Content-Type: application/json
Authorization: Bearer faketoken

{
  "firstName": "Test",
  "lastName": "Resident",
  "cprNr": "010190-1234"
}