### Get server status (test route)
GET http://localhost:7070/
Accept: application/json

### Create new journal entry (multipart upload)
POST http://localhost:7070/api/journalentries
Authorization: Bearer faketoken
Content-Type: multipart/form-data; boundary=---123

---123
Content-Disposition: form-data; name="metadata"

{
  "journalId": 1,
  "title": "Observation of morning routine",
  "type": "DAILY_NOTE",
  "content": "Resident was calm and cooperative. Had breakfast at 8:30.",
  "risk": "LOW"
}
---123
Content-Disposition: form-data; name="files"; filename="observation.pdf"
Content-Type: application/pdf

< ./src/test/resources/files/observation.pdf
---123--

### Create journal entry with no files
POST http://localhost:7070/journals/1/journal-entries
Content-Type: application/json

{
  "journalId": 1,
  "title": "Observation of morning routine",
  "content": "Resident was calm and cooperative. Had breakfast at 8:30.",
  "riskAssessment": "LOW",
  "authorUserId": 3
}
### Remember that authorUserId should correspond to an existing user in your test database. and is hardcoded in controller
### Create a test user
POST http://localhost:7070/users
Content-Type: application/json

{
  "email": "test.careworker@example.com",
  "name": "Test CareWorker"
}

